"""empty message

Revision ID: 25731976ac83
Revises: 959a2d98da2d
Create Date: 2024-01-23 18:14:54.186586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25731976ac83'
down_revision = '959a2d98da2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
