"""empty message

Revision ID: c3e77d83796c
Revises: 0a5f9223b254
Create Date: 2024-01-24 18:41:48.436950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e77d83796c'
down_revision = '0a5f9223b254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorbikes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motorbikes', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
